### ISSUE TITLE
百度网盘过期，数据无法下载，能在分享一下吗？

### ISSUE THREAD

**Issue by daiyizheng** [HuaRui0420/ElixirQueryLLM#1]

**Comment by TCMAI-BJTU** [comment]
已更新

**Comment by qianchen94** [comment]
> 已更新
@TCMAI-BJTU 链接还是过期了

**Comment by Manson-cc** [comment]
@TCMAI-BJTU 求更新，网盘连接过期了，非常感谢

**Comment by chelovek21** [comment]
@TCMAI-BJTU 网盘链接过期了，求更新，非常感谢

**Comment by XuecaiHu** [comment]
@TCMAI-BJTU 网盘链接过期了，求更新，非常感谢

**Comment by zihengh1** [comment]
Hi @TCMAI-BJTU,

Thanks for sharing and great work. I would love to explore this field more. This paper is a decent one that interests us. Would you mind updating your data link? Or moving to a better place for scientific research? Thanks!!

**Comment by TCMAI-BJTU** [comment]
已更新

**Comment by zihengh1** [comment]
Thanks!!
